---
- name: Copy calendar file
  hosts: 54.163.47.38
  become: true

  tasks:
    - name: Copy cal.txt to myscript.sh
      ansible.builtin.copy:
        src: /tmp/cal.txt
        dest: /opt/scripts/myscript.sh
        mode: '0755'
        owner: root
        group: root
