---
- name: Create empty file with 0755 permissions
  hosts: 54.163.47.38# replace with your actual group name
  become: true

  tasks:
    - name: Create file
      ansible.builtin.file:
        path: /tmp/test
        state: touch
        mode: '0755'


